### PR TITLE
Use alter table SQL file instead of modifying existing files for book.year change

### PR DESCRIPTION
**Pull request by jord1e**

### CODE REVIEW

**Comment by jord1e** [comment]
This concept is called _schema migration_ (<https://en.wikipedia.org/wiki/Schema_migration>).

Because the table is already created on other people's database installations, it would give an error if you try to recreate the database. By using an ALTER TABLE statement, it will consistently change the column definition appropriately.

**Comment by julisod** [comment]
I just ran the scripts again since the first script will just delete the database if you have it. Even though that would've been the smartest way to do it. I think the best way could've been to share the alter table part on Discord for those who have already set up the database, because adding it to the scripts is going fail the checks since it gives an error if you already have the year column.

I'm not going to approve the pull request if the checks are failing, and since I took so long to actually ask what this is for, it might not be needed anymore.

What do you think?

**Comment by jord1e** [comment]
In the wikipedia article and the comment, I wrote that you only need to run the file with the ALTER TABLE, not all the scripts.

It's a file for migrations, not a call to reset everything.

> because adding it to the scripts is going fail the checks since it gives an error if you already have the year column.

I don't understand this

**Comment by julisod** [comment]
Sorry for being confusing lol. Yea, you're only supposed to run that one file if you have already set up the database.

Adding the script makes the checks fail because docker is running the scripts from the beginning. If you already have a year column and then run the alter table script, it's going to give an error.

**Comment by julisod** [comment]
This is not needed anymore

**Comment by jord1e** [comment]
Why not...?

**Comment by julisod** [comment]
Everyone in our team has already changed their databases to include the book year, and the next team will run the sql scripts with the book year already in them.

**Pull request closed without merging**
