### PR TITLE
book images backend

### PR DESCRIPTION
**Pull request by Palmitos254**

### CODE REVIEW

**Comment by julisod** [comment]
@Palmitos254 did you notice that there seems to be an error with the sql queries? This PR cannot be merged before that is resolved. You can see it in the failed check:
https://github.com/LibraryProjectGroup/library-project-backend/actions/runs/4552441366/jobs/8027780082?pr=113#step:8:69

**Comment by Palmitos254** [comment]
fixed

**Comment by julisod** [comment]
The checks look nice, good job. There seem to be a lot of unnecessary files labeled OneNote_Table_Of_Contents.onetoc2, I would guess those are there by accident?

**Comment by julisod** [comment]
The checks are working now, but there's still one reason why this cannot be merged. The image column cannot be null, which becomes a problem since the images are not yet in the front end. I can think of two solutions to this.
1. Make the image column optional. If the image column is null, it'd be good to have a placeholder image displayed, but that's a problem for the front end.
2. Wait until we have added this feature to frontend so that there would always be a picture?? Even then, I don't know how we should handle books that you can't find by an ISBN.

Honestly not sure.

**Comment by julisod** [comment]
Yea, the cover image should be optional and we should just add null when there's no cover image.

**Comment by Palmitos254** [comment]
The bookimages can now be null and they can be seen from the main page, my loaned books page and reservations page. The "book cover missing" image is still saved into the database, because i dont know how to change it the way we discussed.

**Comment by Palmitos254** [comment]
Lainat
Pääsivu
Varaukset

**Review by jord1e — APPROVED** [review]

**Pull request merged**
